"""Console output and the markdown cost report. The console shows a findings table, a brief and
each provider's plan; the report (runs/finops-<ts>.md) carries per-provider totals and one
section per provider with the proposed statements. Nothing here executes anything."""

from __future__ import annotations

from pathlib import Path

from rich.panel import Panel
from rich.table import Table

from .config import RUNS_DIR, settings
from .costs import RunLedger, console
from .findings import SEVERITY_ORDER, Finding, FindingSet, ProviderPlan


def banner(title: str, subtitle: str = "") -> None:
    console.rule(f"[bold]{title}[/bold]")
    if subtitle:
        console.print(subtitle)


def _sev_rank(f: Finding) -> int:
    return SEVERITY_ORDER.index(f.severity.value)


def print_findings(fs: FindingSet) -> None:
    if not fs.findings:
        console.print(Panel("No findings. No idle or orphaned resources in scope.", title="finops"))
        console.print(Panel(fs.summary, title="brief"))
        return
    t = Table(
        title=f"finops: {len(fs.findings)} findings, about USD {fs.total_monthly_usd():,.2f}/month (estimated)"
    )
    for c in ("sev", "provider", "finding", "resource", "est. USD/mo"):
        t.add_column(c, justify="right" if c == "est. USD/mo" else "left")
    for f in sorted(
        fs.findings, key=lambda x: (-_sev_rank(x), -(x.monthly_cost_estimate_usd or 0))
    ):
        cost = "" if f.monthly_cost_estimate_usd is None else f"{f.monthly_cost_estimate_usd:,.2f}"
        t.add_row(f.severity.value, f.provider, f.finding_type, f.resource[:70], cost)
    console.print(t)
    console.print(Panel(fs.summary, title="brief"))


def print_plan(plan: ProviderPlan) -> None:
    console.rule(f"{plan.provider}: proposed deletions (for review, not executed)")
    console.print(plan.rationale)
    for p in plan.sorted_proposed():
        console.print(
            f"[green]USD {p.monthly_cost_estimate_usd:7.2f}/mo[/]  {p.resource}  - {p.reason}"
        )
        console.print(f"    {p.statement}")
    for d in plan.deferred:
        console.print(f"[yellow]deferred[/]  {d.resource}  - {d.reason}")
    console.print(
        f"{len(plan.proposed)} proposed (about USD {plan.proposed_monthly_usd():,.2f}/month), "
        f"{len(plan.deferred)} deferred"
    )


def _md_table(header: list[str], rows: list[list[str]]) -> list[str]:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return out


def ledger_markdown(ledger: RunLedger) -> list[str]:
    rows = []
    for e in ledger.entries:
        cost = f"{e.cost_usd:.4f}" if e.cost_usd is not None else "n/a"
        rows.append(
            [
                e.label,
                e.model,
                str(e.requests),
                f"{e.input_tokens:,}",
                f"{e.cached_tokens:,}",
                f"{e.output_tokens:,}",
                f"{e.reasoning_tokens:,}",
                f"{e.tool_calls} ({e.select_calls} select, {e.mutation_calls} mutation)",
                cost,
            ]
        )
    rows.append(
        [
            "total",
            "",
            str(sum(e.requests for e in ledger.entries)),
            f"{sum(e.input_tokens for e in ledger.entries):,}",
            f"{sum(e.cached_tokens for e in ledger.entries):,}",
            f"{sum(e.output_tokens for e in ledger.entries):,}",
            f"{sum(e.reasoning_tokens for e in ledger.entries):,}",
            f"{sum(e.tool_calls for e in ledger.entries)} "
            f"({sum(e.select_calls for e in ledger.entries)} select, "
            f"{sum(e.mutation_calls for e in ledger.entries)} mutation)",
            f"{ledger.total_cost_usd:.4f}",
        ]
    )
    return _md_table(
        ["step", "model", "req", "input", "cached", "output", "reasoning", "tool calls", "USD"],
        rows,
    )


def write_markdown_report(
    fs: FindingSet,
    plans: list[ProviderPlan],
    ledger: RunLedger,
    providers: list[str],
    out_dir: Path | None = None,
) -> Path:
    s = settings()
    out_dir = RUNS_DIR if out_dir is None else out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"finops-{ledger.stamp}.md"
    by_provider = fs.by_provider()
    plan_of = {p.provider: p for p in plans}
    lines = [
        f"# FinOps cost report - {ledger.stamp}",
        "",
        "Generated by a scheduled, read-only sweep (finops/). Every line is backed by a SELECT against",
        "a cloud control plane through the StackQL MCP server in read_only mode; nothing was changed.",
        "Monthly figures are list-price estimates computed in SQL, not billing data. The statements",
        "below are proposals for human review; this program never executes them.",
        "",
        f"- run started: {ledger.started_at.isoformat(timespec='seconds')}",
        f"- providers swept: {', '.join(providers)}",
        f"- models: sweep={s.sweep.model}, reasoning={s.reasoning.model}",
        f"- snapshot age threshold: {s.snapshot_max_age_days} days",
        f"- trace: {ledger.trace_url or 'n/a'}",
        "",
        "## Summary",
        "",
        fs.summary,
        "",
    ]
    rows = []
    for provider in providers:
        group = by_provider.get(provider, [])
        plan = plan_of.get(provider)
        total = round(sum(f.monthly_cost_estimate_usd or 0.0 for f in group), 2)
        rows.append(
            [
                provider,
                str(len(group)),
                f"{total:,.2f}",
                str(len(plan.proposed)) if plan else "-",
                f"{plan.proposed_monthly_usd():,.2f}" if plan else "-",
                str(len(plan.deferred)) if plan else "-",
            ]
        )
    rows.append(
        [
            "total",
            str(len(fs.findings)),
            f"{fs.total_monthly_usd():,.2f}",
            str(sum(len(p.proposed) for p in plans)),
            f"{sum(p.proposed_monthly_usd() for p in plans):,.2f}",
            str(sum(len(p.deferred) for p in plans)),
        ]
    )
    lines += _md_table(
        [
            "provider",
            "findings",
            "est. USD/month (all)",
            "proposed now",
            "est. USD/month (proposed)",
            "deferred",
        ],
        rows,
    )
    lines.append("")
    for provider in providers:
        group = by_provider.get(provider, [])
        plan = plan_of.get(provider)
        lines += [f"## {provider}", ""]
        if not group:
            lines += ["No findings.", ""]
            continue
        frows = []
        for f in sorted(group, key=lambda x: -(x.monthly_cost_estimate_usd or 0)):
            cost = (
                "" if f.monthly_cost_estimate_usd is None else f"{f.monthly_cost_estimate_usd:,.2f}"
            )
            frows.append([f.severity.value, f.finding_type, f"`{f.resource}`", f.title, cost])
        lines += _md_table(["sev", "finding", "resource", "title", "est. USD/mo"], frows)
        lines.append("")
        if plan is None:
            lines += ["Reasoning tier not run for this provider; no statements proposed.", ""]
            continue
        lines += [plan.rationale, ""]
        lines += [
            f"Proposed statements, ordered by estimated savings ({len(plan.proposed)} statements, "
            f"about USD {plan.proposed_monthly_usd():,.2f}/month) - for human review, not executed:",
            "",
            "```sql",
        ]
        for p in plan.sorted_proposed():
            lines.append(
                f"-- {p.resource}  est. USD {p.monthly_cost_estimate_usd:,.2f}/mo  {p.reason}"
            )
            lines.append(p.statement.strip().rstrip(";") + ";")
            lines.append("")
        if lines[-1] == "":
            lines.pop()
        lines += ["```", ""]
        if plan.deferred:
            lines += ["Deferred:", ""]
            lines += [f"- `{d.resource}`: {d.reason}" for d in plan.deferred]
            lines.append("")
    lines += ["## Evidence", ""]
    for f in fs.findings:
        lines += [
            f"- `{f.resource}` ({f.provider}, {f.finding_type}, query `finops/queries/{f.query_id.removeprefix('finops/')}.sql`): {f.evidence}"
        ]
    lines += ["", "## Run cost", ""]
    lines += ledger_markdown(ledger)
    lines += ["", f"StackQL MCP audit log: `{s.mcp_audit_log}`", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
