/**
 * Console output and the recertification report. No UI beyond the terminal and files: the
 * artifact of this use case is a markdown report an entitlement owner works through, deciding
 * confirm or revoke per line. Nothing in the report has been executed.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { RUNS_DIR, tenancyLines, type Settings } from './config.ts';
import { table, timestamp } from './text.ts';
import { fingerprint, sortBySeverity, type Assessment, type FindingSet } from './schemas.ts';

export function banner(title: string, subtitle: string): void {
  console.log(`\n${'='.repeat(78)}\n${title}\n${subtitle}\n${'='.repeat(78)}`);
}

export function printFindings(fs: FindingSet): void {
  console.log(`\nfindings (${fs.findings.length})`);
  if (!fs.findings.length) {
    console.log('  none');
  } else {
    console.log(
      table(
        ['sev', 'provider', 'principal / resource', 'finding', 'fp'],
        sortBySeverity(fs.findings).map((f) => [f.severity, f.provider, f.resource, f.title, fingerprint(f)]),
      ),
    );
  }
  console.log(`\nbrief: ${fs.summary}`);
}

export function printAssessments(assessments: Assessment[], summary: string): void {
  console.log('\nassessment (reasoning tier)');
  for (const a of assessments) {
    console.log(
      `  ${a.finding_fingerprint} material=${a.material} confirm-by: ${a.confirmer}\n    ${a.rationale.slice(0, 300)}`,
    );
  }
  if (summary) console.log(`\n${summary}`);
}

export function recertificationMarkdown(
  s: Settings,
  fs: FindingSet,
  assessments: Assessment[],
  executiveSummary: string,
  ts: string,
  traceUrl: string | null,
): string {
  const byFp = new Map(assessments.map((a) => [a.finding_fingerprint, a]));
  const lines: string[] = [
    `# Entitlements recertification - ${ts}`,
    '',
    'Generated by a scheduled, read-only sweep. Every line is backed by a SELECT the agent discovered',
    'and ran against a control plane through the StackQL MCP server; nothing was changed. Entitlement',
    'owners confirm or revoke each grant below. The removal statements are drafted for review and were',
    'not executed.',
    '',
    '## Scope',
    '',
    ...tenancyLines(s).map((l) => `- ${l}`),
    `- IdP provider: ${s.idpProvider}`,
    ...(traceUrl ? [`- Agent trace: ${traceUrl}`] : []),
    '',
    '## Summary',
    '',
    fs.summary,
    '',
  ];
  if (executiveSummary) lines.push('## Reasoning tier assessment', '', executiveSummary, '');
  lines.push(
    '## Entitlements requiring a decision',
    '',
    '| severity | provider | principal | finding | confirm / revoke |',
    '|---|---|---|---|---|',
  );
  for (const f of sortBySeverity(fs.findings)) {
    lines.push(`| ${f.severity} | ${f.provider} | \`${f.resource}\` | ${f.title} | [ ] confirm  [ ] revoke |`);
  }
  if (!fs.findings.length) lines.push('| - | - | - | no findings | - |');
  lines.push('', '## Evidence and proposed statements', '');
  for (const f of sortBySeverity(fs.findings)) {
    const fp = fingerprint(f);
    lines.push(
      `### ${f.title}`,
      '',
      `- fingerprint: \`${fp}\``,
      `- provider: ${f.provider}`,
      `- principal / resource: \`${f.resource}\``,
      `- finding type: ${f.finding_type}`,
      `- query source: \`${f.query_id}\` (a query library id, an example under entitlements/queries/examples/, or discovered at run time)`,
      '',
      'Evidence:',
      '',
      '```',
      f.evidence,
      '```',
      '',
      'Proposed remediation (for review, not executed):',
      '',
      '```sql',
      f.proposed_remediation,
      '```',
      '',
    );
    const a = byFp.get(fp);
    if (a) {
      lines.push(
        `Assessment: material=${a.material}. ${a.rationale}`,
        '',
        `- confirm or revoke by: ${a.confirmer}`,
        `- least-privilege alternative: ${a.least_privilege_alternative}`,
        `- blast radius: ${a.blast_radius}`,
        '',
        'Removal statement (drafted by the reasoning tier, never executed by this program):',
        '',
        '```sql',
        a.removal_statement,
        '```',
        '',
      );
    }
  }
  return lines.join('\n');
}

export function writeRecertificationReport(
  s: Settings,
  fs: FindingSet,
  assessments: Assessment[],
  executiveSummary: string,
  startedAt: Date,
  traceUrl: string | null,
): string {
  mkdirSync(RUNS_DIR, { recursive: true });
  const ts = timestamp(startedAt);
  const p = path.join(RUNS_DIR, `entitlements-recertification-${ts}.md`);
  writeFileSync(p, recertificationMarkdown(s, fs, assessments, executiveSummary, ts, traceUrl), 'utf8');
  return p;
}
